language: ruby
# only run CI-builds on master branch
branches:
  only:
#  - master
  - docs
rvm:
- 2.2.3
# set execution permission on our build script
before_script:
 - chmod +x ./build-jekyll.sh
 - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
 - sudo dpkg -i ./pandoc-1.19.2.1-1-amd64.deb
 - sudo apt-get update 
 - sudo apt-get install texlive-full ssed
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./build-jekyll.sh
exclude: [vendor]
sudo: false